name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
     - "**.css"

permissions:
  contents: write

jobs:
  minify-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v4
    - run: |
        npm install postcss-cli @csstools/postcss-nesting-experimental @csstools/postcss-minify --save-dev
        find . -name "*.css" -not -path "./dist/*" | while IFS= read -r file; do
          npx postcss "$file" --output "dist/$file" --use @csstools/postcss-nesting-experimental @csstools/postcss-minify --no-map --verbose
        done
      shell: bash
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
        clean: true
